" File: $HOME/.vimrc
" Made by iBug
" Jun 29, 2020
" iBug's Vim RC file
" Vim 8.1

set nocompatible
set timeoutlen=500 ttimeoutlen=50
set showcmd number ruler background=dark showmatch
set autoindent cindent smartindent
set tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab
set wrapscan ignorecase incsearch hlsearch
set whichwrap+=<,>,[,]
set backspace=2 laststatus=2
set foldenable foldmethod=manual
set formatoptions-=cro
set autoread nobackup noswapfile confirm
set linebreak
set magic iskeyword+=_
set mouse=a selection=exclusive selectmode=mouse,key
set autoread
set cursorline cursorcolumn
syntax on

map q <NOP>
map Q <NOP>
map <M-v> <C-v>
let mapleader="!"

let mapleader=" "
map <Leader> <NOP>
noremap <Leader><Left> <C-W>h
noremap <Leader><Down> <C-W>j
noremap <Leader><Up> <C-W>k
noremap <Leader><Right> <C-W>l

filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

autocmd FileType sh,javascript,html,htmldjango,liquid,css,scss,yaml,ruby,vb,sql,pug,vue set tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType html,htmldjango,css,make,text set noexpandtab
autocmd FileType liquid set expandtab
autocmd FileType markdown set shiftwidth=2
autocmd FileType asm set tabstop=8 shiftwidth=8 softtabstop=8 noexpandtab
autocmd FileType * set formatoptions-=cro formatoptions+=m
autocmd BufNewFile *.[ch],*.[ch]pp exec ":call CAddFileInfo()"
autocmd BufWritePre * :%s/^\s\+$//e " Only trim empty lines

func! CAddFileInfo()
    call setline(1, "// File: ".expand("%:t"))
    call append(line("."), "// Author: iBug")
    call append(line(".")+1, "")
    normal G
endfunc

:nnoremap <F5> "=strftime("%Y-%m-%dT%H:%M:%S%z")<CR>p
:inoremap <F5> <C-R>=strftime("%Y-%m-%dT%H:%M:%S%z")<CR>

set runtimepath+=~/proj/tabnine-vim

"set runtimepath+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
"Plugin 'spacewander/openresty-vim'
"call vundle#end()
