" File: $HOME/.vimrc
" Made by iBug
" Jan 1, 2020
" iBug's Vim RC file
" Vim 8.1

set nocompatible
set timeoutlen=500 ttimeoutlen=50
set showcmd number ruler background=dark showmatch
set autoindent cindent smartindent
set tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab
set wrapscan ignorecase incsearch hlsearch
set whichwrap+=<,>,[,]
set backspace=2 laststatus=2
set foldenable foldmethod=manual
set formatoptions-=cro
set autoread nobackup noswapfile confirm
set linebreak
set magic iskeyword+=_
set mouse=a selection=exclusive selectmode=mouse,key
syntax on

map q <NOP>
map Q <NOP>

let mapleader=" "
map <Leader> <NOP>
noremap <Leader><Left> <C-W>h
noremap <Leader><Down> <C-W>j
noremap <Leader><Up> <C-W>k
noremap <Leader><Right> <C-W>l

filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

autocmd FileType sh,javascript,html,htmldjango,css,scss,yaml,ruby,vb,sql set tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType markdown set shiftwidth=2
autocmd FileType html,htmldjango,css,scss,make,text set noexpandtab
autocmd FileType * set formatoptions-=cro formatoptions+=m
autocmd BufNewFile *.[ch],*.[ch]pp exec ":call CAddFileInfo()"
autocmd BufWritePre * :%s/^\s\+$//e " Only trim empty lines

func! CAddFileInfo()
    call setline(1, "// File: ".expand("%:t"))
    call append(line("."), "// Author: iBug")
    call append(line(".")+1, "")
    normal G
endfunc
