" File: $HOME/.vimrc
" Made by iBug
" May 12, 2019
" Minimal Vim RC file
" Vim 8.0

set nocompatible
set timeoutlen=200
set showcmd number ruler background=dark
set noshowmatch
set autoindent smartindent
set tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab
set wrapscan ignorecase incsearch hlsearch
set whichwrap+=<,>,[,]
set backspace=2 laststatus=2
set foldenable foldmethod=manual
set formatoptions-=cro
set noautoread nobackup noswapfile confirm
"set noerrorbell
set magic iskeyword+=_
set mouse=a selection=exclusive selectmode=mouse,key
syntax on

map <C-S> :w<CR>
imap <C-S> <Esc>:w<CR>a
"map <C-W> :q<CR>
"imap <C-W> <Esc>:q<CR>
map <C-h> <C-W>h
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-l> <C-W>l
map <C-Left> <C-W>h
map <C-Down> <C-W>j
map <C-Up> <C-W>k
map <C-Right> <C-W>l

filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

autocmd FileType sh,javascript,html,css,scss,yaml,ruby,vb,sql set tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType html,htmldjango,css,scss,make,text set noexpandtab
autocmd FileType * set formatoptions-=cro
autocmd FileType c,cpp map <F9> <Esc>:w<CR>:call GccCompile()<CR>
autocmd FileType c,cpp map <F10> <Esc>:w<CR>:call RunProgram()<CR>
autocmd FileType c,cpp map <F11> <Esc>:w<CR>:call GccCompile()<CR>:call RunProgram()<CR>
autocmd FileType sh,python map <F11> <Esc>:w<CR>:call RunScript()<CR>
autocmd BufNewFile *.[ch],*.[ch]pp exec ":call CAddFileInfo()"
autocmd BufNewFile,BufRead *.html set filetype=htmldjango

func! CAddFileInfo()
    call setline(1, "// File: ".expand("%:t"))
    call append(line("."), "// Author: iBug")
    call append(line(".")+1, "")
    normal G
endfunc

func! GccCompile()
    exec "w"
    if filereadable("Makefile")
        exec "silent !echo 'make'"
        exec "!make"
    elseif &filetype == "c"
        exec "silent !echo \"gcc % -o %< -O2 -s\""
        exec "!gcc % -o %< -O2 -s"
    elseif &filetype == "cpp"
        exec "silent !echo \"g++ % -o %< -O2 -s\""
        exec "!g++ % -o %< -O2 -s"
    endif
endfunc

func! RunProgram()
    exec "! ./%<"
endfunc

func! RunScript()
    exec "! ./%"
endfunc
